name: wair_d_distal
channels:
  - defaults
  - conda-forge
  - plotly
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - pip=23.3.1
  - python=3.11.8
  - conda-lock=1.4.0
  - hydra-core=1.3.2
  - pytorch-lightning=2.2.1
  - rich=13.3.5
  - scikit-image=0.22.0
  - plotly=5.19.0
  - folium=0.17.0
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - torchvision=0.16.1
  - seaborn=0.12.2
  - openpyxl=3.0.10
  - tqdm=4.65.0
  - python-dotenv=0.21.0
  - transformers=4.37.2
  - altair=5.0.1
  - tabulate=0.9.0
  - streamlit=1.32.0
  - wandb=0.16.3
  - scipy=1.11.4
  - osmnx=1.9.1
  - geopy=2.4.1
  - pyproj=3.6.1
  - shapely=2.0.3
  - numpy=1.26.4
  - ocl-icd-system=1.0.0
  #  - accelerate=0.28.0
  - ftfy=5.8
  - pocl=5.0
  - opencv=4.9.0
  - pip:
      - torch==2.2.1
      - triton==2.2.0
      - p_tqdm==1.4.0
      - aim==3.18.1
      - numba==0.61.0
      - segmentation-models-pytorch==0.4.0
      - piq==0.8.0
      - kaggle==1.7.4.2