# @package _global_
name: train
seed: 0
print_config: True
ignore_warnings: True
terminal_col: null
terminal_row: 24

defaults:
  - datamodule: mlsp
  - optimizer: adam
  - scheduler: null
  - algorithm: mlsp
  - network: mlsp_unet
  - trainer: default
  - callbacks: [ model_checkpoint_0 ]
  - loggers: [ aim ]
  - strategy: null
  - _self_

ckpt_path: null

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S.%f}
  job:
    chdir: True