_target_: src.datamodules.MLSPDatamodule

name: icassp_task1
batch_size: 8
num_workers: 6

data_dir: ${oc.env:ICASSP_ORIG_PATH}
mlsp_task1: True
inference: False

freqs_mhz: [ 868, 1800, 3500 ]
pl_clip: null
freqs: [ 1, 2, 3 ]
val_freq: [ 1, 2, 3 ]
val_buildings: [ 1, 2, 3 ]
kaggle_task1_path: ${oc.env:KAGGLE_TASK1_PATH}
kaggle_task2_path: ${oc.env:KAGGLE_TASK2_PATH}
kaggle_freqs_mhz: [ 868, 2400 ]
sparsity_range: [ -0.00166666666667, 0.005 ] # This means 0 with 25% probability and random from [0, 0.005] with 75% probability
reps_per_epoch: 10

# Data augmentation parameters
augment_val: True
aug_p: 0.5
walls_aug_p: 0.99
transmittance_range: [ 2, 18 ]
angle_range: [ -30, 30 ]
scale_range: [ 0.6666666666666667, 1.5 ]
flip_vertical: True
flip_horizontal: True
cardinal_rotation: True